spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    servlet:
      path: /api

EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
jwt:
  secret: ${JWT_SECRET_KEY}
