spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
logging:
  level:
    org.hibernate.SQL: debug
app:
  clientId: ${TWINKLE_CLIENT_ID}
  redirectUrl: ${TWINKLE_REDIRECT_URL}
  secretKey: ${TWINKLE_SECRET_KEY}
  bankUrl: ${TWINKLE_BANK_URL}