spring:
  data:
    redis:
      host: ${SERVER_URL}
      port: 6379
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${SERVER_URL}:${DEV_TRIP_MONGODB_BINDING_PORT}/?authSource=admin
      database: ${MONGO_INITDB_DATABASE}
  rabbitmq:
    host: ${SERVER_URL}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
#  mvc:
#    servlet:
#      path: /api

EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
jwt:
  secret: ${JWT_SECRET_KEY}
rabbitmq:
  queue:
    name: chat.queue
  exchange:
    name: chat.exchange
  routing:
    key: room.
