version: "3"
services:

  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: test_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: <db이름>
      MYSQL_ROOT_PASSWORD: <db패스워드 지정>

  spring:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: docker-actions-spring-dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/<db이름>
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: <db 패스워드>