spring:
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  profiles: dev
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  profiles: prod
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none