spring:
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
logging:
  level:
    org.hibernate.SQL: debug